### ISSUE TITLE
afterBuildMethod is not called on decorator, but only on base instance

### ISSUE THREAD

**Issue by netdust** [lucatume/di52#61]
when providing afterbuildmethods to a bindDecorators call, once the container creates the instances, the afterbuildmethods are only called on the base class. the afterbuildmethods should be called on the first decorator so the calls goes down the chain, ultimately to the base class as last one.

**Comment by lucatume** [comment]
Hi @netdust,

thanks for taking the time to open an issue.

Could you provide a minimal example to reproduce the issue?

**Comment by netdust** [comment]
```php
<?php

use lucatume\DI52\Container;

$container = new Container();

// Decorators are built left to right, outer decorators are listed first.
 $container->bindDecorators(PostEndpoint::class, [
		    LoggingEndpoint::class,
                    CachingEndpoint::class,
		    BaseEndpoint::class
	    ],
           ['add_actions']
 );

$container->get(PostEndpoint::class);
```

This should call the `add_action` method on `LoggingEndpoint` first, then from there all the way to `BaseEndPoint`. But instead it calls the method directly on `BaseEndpoint`, skipping the decorators.

**Comment by lucatume** [comment]
Thanks for providing an example.

Since we're talking about the decorator pattern here, the `add_actions` after-build method should be called on the outer decorator only; i.e. the `LoggingEndpoint` one.
It should be, then, up to the `LoggingEndpoint` to call `CachingEndpoint::add_actions` that should, in turn, call the `BaseEndpoint::add_actions` method.

I will look into this with this frame of mind: the `add_actions` method should be called after the `PostEndpoint` is built, whatever is the outer decorator.

**Comment by netdust** [comment]
👌thx!
